language: generic
sudo: required 
services:
  - docker 

before_install: 
  - docker build -t sergiopichardo/react-test -f ./client/Dockerfile.dev ./client


script: 
  docker run -e CI=true sergiopichardo/react-test npm test

