language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t sergiopichardo/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true sergiopichardo/react-test npm test -- --coverage
after_success:
  - docker build -t sergiopichardo/multi-client ./client
  - docker build -t sergiopichardo/multi-nginx ./nginx
  - docker build -t sergiopichardo/multi-server ./server
  - docker build -t sergiopichardo/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push sergiopichardo/multi-client
  - docker push sergiopichardo/multi-nginx
  - docker push sergiopichardo/multi-server
  - docker push sergiopichardo/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker-application
  env: multi-docker-application-env
  bucket_name: elasticbeanstalk-us-east-1-905939075673
  bucket_path: multi-docker-application
  edge: true    # for experimental deployment features provided by travis
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on: 
    branch: master